---
title: Páginas de Error
sidebar_label: Páginas de Error
---

## Página 404 {#404-page}

Una página 404 puede ser requerida muy a menudo por lo que Blitz
proporciona una página estatica 404 por defecto sin tener que añadir
archivos adicionales.

### Customizando La Pagina 404 {#customizing-the-404-page}

Para crear una página 404 customizada puede crear un archivo tal como:
`app/pages/404.js`. Este archivo se genera estáticamente en el momento de
la compilación.

```jsx
// app/pages/404.js
export default function Custom404() {
  return <h1>404 - Page Not Found</h1>
}
```

## Pagina 500 {#500-page}

Por defecto Blitz proporciona una página de error 500 que coincide con el
estilo de la página 404. Esta página no esta optimizada estáticamente ya
que permite errores del lado del servidor para ser reportados. Esta es la
razon por la que 404 y 500 (otros errores) están separados.

### Personalización De la Página de Error {#customizing-the-error-page}

Los errores 500 se manejan tanto del lado del cliente como del lado del
servidor por medio del componente `Error`. Si deseas anularlo, define el
archivo `app/pages/_error.js` y añade el código siguiente:

```jsx
function Error({ statusCode }) {
  return (
    <p>
      {statusCode
        ? `An error ${statusCode} occurred on server`
        : "An error occurred on client"}
    </p>
  )
}

Error.getInitialProps = ({ res, err }) => {
  const statusCode = res ? res.statusCode : err ? err.statusCode : 404
  return { statusCode }
}

export default Error
```

> `app/pages/_error.js` es sólo utilizado en producción. En desarrollo,
> obtendrá un error con la pila de llamadas para saber dónde se originó el
> error.

## Personalizando el Componente Error Boundary Fallback {#custom-error-boundary-component}

El archivo por defecto `app/pages/_app.tsx` configura un límite de error
que captura los errores que ocurren durante el renderizado, en el lado del
cliente. Esto también detecta errores dentro de `useQuery` o` useMutation`
porque ocurren en suspenso.

En esencia, la configuración por defecto es:

```tsx
export default function App({ Component, pageProps }: AppProps) {
  return (
    <ErrorBoundary FallbackComponent={RootErrorFallback} {...etc}>
      {getLayout(<Component {...pageProps} />)}
    </ErrorBoundary>
  )
}
```

`RootErrorFallback` se renderiza cuando se produce un error dentro de
renderización ,o una mutación o consulta suspendida. Por defecto:

```tsx
function RootErrorFallback({
  error,
  resetErrorBoundary,
}: ErrorFallbackProps) {
  if (error instanceof AuthenticationError) {
    return <LoginForm onSuccess={resetErrorBoundary} />
  } else if (error instanceof AuthorizationError) {
    return (
      <ErrorComponent
        statusCode={error.statusCode}
        title="Sorry, you are not authorized to access this"
      />
    )
  } else {
    return (
      <ErrorComponent
        statusCode={error.statusCode || 400}
        title={error.message || error.name}
      />
    )
  }
}
```

### Componente de error de autenticación (401) {#custom-authentication-error-component}

Si su consulta, mutación o función de renderizar
`throw new AuthenticationError ()` cuando el usuario no está autenticado,
puede detectar que dentro de la reserva de error:

If your query, mutation, or render function
`throw new AuthenticationError()` when the user is not authenticated, you
can detect that within the error fallback:

```tsx
function RootErrorFallback({
  error,
  resetErrorBoundary,
}: ErrorFallbackProps) {
  if (error instanceof AuthenticationError) {
    return <MyCustomError error={error} onRetry={resetErrorBoundary} />
  }
  return (
    <ErrorComponent
      statusCode={error.statusCode || 400}
      title={error.message || error.name}
    />
  )
}
```

### Componente de error de autorización (403) {#custom-authorization-error-component}

Su función de consulta, mutación o renderización puede llamar a
`throw new AuthorizationError ()` cuando un usuario está autenticado pero
no autorizado para hacer algo. El error fallback puede manejar eso:

```tsx
function RootErrorFallback({
  error,
  resetErrorBoundary,
}: ErrorFallbackProps) {
  if (error instanceof AuthorizationError) {
    return <MyCustomError error={error} onRetry={resetErrorBoundary} />
  }
  return (
    <ErrorComponent
      statusCode={error.statusCode || 400}
      title={error.message || error.name}
    />
  )
}
```

## Reutilización de la página de error incorporada {#reusing-the-built-in-error-page}

Puede representar la página de error incorporada importando
`ErrorComponent`.

Acepta dos props:

- `statusCode` - un número para mostrar como código de error
- `title` - una cadena para mostrar como mensaje de error

```jsx
import { ErrorComponent } from "blitz"

export default function Page() {
  return <ErrorComponent statusCode={404} />
}
```

```jsx
import { ErrorComponent } from "blitz"

export default function Page() {
  return <ErrorComponent statusCode={401} title="Unauthorized" />
}
```
